### ISSUE TITLE
Can't find/delete Language box

### ISSUE THREAD

**Issue by djmcalleja** [softdevteam/eco#130]
I found a bug while going through the Eco tutorial. I created a language box for Image, left it blank, and created a new language box in the same place, and then I was unable to delete one of the language boxes.

In the image, there is a image in the parsing pane that can't be found.

![bug_invisible](https://cloud.githubusercontent.com/assets/17003711/15827687/0ea53e78-2c04-11e6-9ab6-de333e854d9c.png)

**Comment by ptersilie** [comment]
I was just about to fix this, but once I thought a bit more about it I'm not sure what behaviour is the most user friendly. Should the box just be deleted when I move the cursor before entering something into it. Or should the user be able to reselect an empty box? At the moment you can get back into the box by moving the cursor right before it and press `Ctrl+Shift+L`. However for this to work, you need to know where the box is, which is difficult as there is no visible cue. In the past I think you could also enter the box by double clicking the parsing status on the right, but this currently leads to an endless loop.

So there are a few ways how to fix this:
1. Delete the box if the cursor moves away from it, and the user hasn't typed anything into it
2. Add a visual cue in the editor to find empty language boxes
3. Fix double clicking on the parsing status to re-enter the box (probably in combination with 2.)

@snim2, @ltratt: maybe you guys also have some input on this

I personally tend to solutions 2. and 3., but mainly as 1. is harder to do than I thought. :wink:

**Comment by snim2** [comment]
When Eco is a bit slow (and @djmcalleja was running Eco in a VirturalBox) the only indication that a box exists is the parsing status. You can't use that to find out where the boxes are on the screen, and if you happen to have one that is empty and invisible, there is no way out except to delete the file and start again.

For that reason, I would tend to go with your solutions 2 and 3 combined, but perhaps @djmcalleja has some thoughts on this, since he was driving.

**Comment by ltratt** [comment]
I think "invisible" language boxes are a bit of a problem, because unless you have the parsing status tab open, you don't even know they're there. And most people won't have the parsing status open.

One possibility is to say a language box is always 1 character wide (even if it doesn't contain any characters), so it can't ever be forgotten.

If that's unacceptable, then i think solution 1 is probably the most user-friendly option.

**Comment by djmcalleja** [comment]
I think combining 2 and 3 would be a good solution. I think it might be useful in general if you could focus on language boxes by clicking them in the parsing status pane. Solution 1 might be annoying if the user creates a language box, but wants to edit something else quickly and clicks away, and then the language box disappears (probably only a problem if it takes your computer 30 seconds to make the language box).

**Comment by ptersilie** [comment]
@snim2 As I said above you can get back into the box using `Ctrl+Shift+L` but you need to know where the box is, as there is currently no hint, which is not very user friendly.

@ltratt I thought about having this 1 char wide language box, but I don't think an empty language box should have an impact on the positions of the other characters.

@djmcalleja I agree that Solution 1 might be confusing for the reason you mentioned. I think the reason you language boxes are slow is because the first time you create a language box of a certain language Eco generates a parser for that language. The result is then cached so in the future creating language boxes should be faster (note that some big languages, e.g. Java, PHP, still take a while to load even when cached).

Given your input, I decided to have a go at making empty language boxes more visible. I'll see what I can come up with and report back when I have something.

**Comment by ptersilie** [comment]
This is how my current solution looks like:
![emptylboxhints](https://cloud.githubusercontent.com/assets/375552/15860572/851f1c0a-2cc1-11e6-8250-309963342b84.png)

The first box has the cursor inside it, so the usual brackets are visible. The next box is a box with text in it. That box also contains a nested empty box (blue arrow). The fourth box is a top level empty box.

**Comment by snim2** [comment]
Certainly looks like an improvement to me.

**Comment by ltratt** [comment]
+1

**Comment by ptersilie** [comment]
I'll need to fix one more thing and then I'll wait for @djmcalleja to see what he thinks and let him know when it's ready to merge.

**Comment by djmcalleja** [comment]
That looks good

**Comment by ptersilie** [comment]
@djmcalleja If you have tried out the branch and are happy with the changes (maybe test a few things with language boxes to see that it works), then this is ready to merge.

I also fixed the parsing status double click, which should now jump to errors and inside boxes.

**Comment by djmcalleja** [comment]
@ptersilie Alright, I'll try it now and let you know.

**Comment by djmcalleja** [comment]
Fixed in PR #132
