### ISSUE TITLE
Middle ground between Eco and MPS

### ISSUE THREAD

**Issue by molikto** [softdevteam/eco#270]
Hello! I found Eco an interesting idea. Have you considered a middle ground between Eco and MPS, where lexicons is structurally edited (meaning: e.g. highlight is not derived property, but an intrinsic property of a lexicon), but syntax is incrementally parsed?

I wrote a small blog about this idea: https://molikto.github.io/posts/09-structural-middle-grounds.html 

What do you think?

**Comment by ptersilie** [comment]
I'm not sure I follow. Could you explain what you mean by "lexicons" in this context?

**Comment by ltratt** [comment]
I *think* that Eco already does what @molikto desires, because Eco doesn't store anything as a string: it really stores things as a tree. Put another way, both MPS and Eco use virtually the same underlying data-structure (MPS an abstract syntax tree, Eco a parse tree): the big difference is how one edits those trees. In MPS, you have to respect the tree structure; in Eco, you can pretend it's flat text (though it isn't). So, for example, Eco's display is a pretty-print of the parse tree (i.e. syntax colouring uses the underlying token/lexeme type: it's not cheating like a lot of syntax colourers!).

**Comment by molikto** [comment]
@ltratt 

Hello! Thanks for the reply.

I might have something a little bit different in mind:

By "tokens is edited structurally" I means for example in java `"\"` is invalid string literal because escape chararcters. But image tokens is never re-lexed in Eco, and the incremental parsing algorithm works on diffs of token list instead of diffs of strings, so each edit action (delete, insertion) produce a diff of tokens list, and the parsing algorithm might change the parse tree, but never change the type of tokens.


This way we don't need escape characters, also we can have tokens that contains the exact same characters (the cubical type theory exmaple in my blog post), but they are different token types (one number literal token, one dimension literal token), and displayed using different fonts.

So a structual editor the essentail data structure is a AST. text editor works with strings. This editor works with token strings, where the type of token is intrinsic property rather than derived property. 

So in this editor, typing "+" inside "11" will not break the number literal token into 3 pieces by default. Because tokens is edited structually, although things like this can be accepted by custom logic. But I think most of time these kind of edits is not desired or very randomly people have to do these kind of edits.

The good thing about this is:

You can do automate pretty printing, by pretty printing I means like in Lamdu or Hazel, the line breaking is entirely controlled by the editor (this have good and bad consequences, but we can image ways to remedy the bad ones)

Also you can have more cusomatic effects, like in MPS you can have complex math symbols (details should be polished out, but one can have a rough idea how this can be done)

You don't have escape characters, don't need to restrict that identifers cannot have certain name (keywords)

I think this approach has a lot of benefits of structural editors, and it is conceptionally much simple and works almost like a text editor (except syntax always stays valid, but I think IntelliJ IDEA as a text editor already have some advanced features reguarding this, like inputing `{` alone will choose a correct place to input a closing "}")

**Comment by ltratt** [comment]
I'm not entirely sure I understand, but I think I have a rough idea what you're suggesting. Two comments.

First, to some extent, the grammar author can control how things are edited by defining tokens in different ways: if you want finer-grained editing, you can sometimes define tokens in different ways to achieve that effect. However, I don't think that's general enough for what you want.

Second, Eco has the concept of *multinodes* (see p115 in the PDF of https://diekmann.co.uk/diekmann_phd.pdf) which are can be thought of as tokens with subtokens. They're particularly useful for things like comments, but they might address your overall point?

**Comment by ptersilie** [comment]
> This way we don't need escape characters, also we can have tokens that contains the exact same characters (the cubical type theory exmaple in my blog post), but they are different token types (one number literal token, one dimension literal token), and displayed using different fonts.

It is possible to add a stateful lexer to Eco which could lex the same token values into different token types depending on where they occur in the program. However, this tends to over-complicate the language unnecessarily in my opinion.

Note that we can still display the same token type differently within the editor using information from the parse tree (e.g. by looking at the tokens parent which may not always be the same). Eco uses this in Python for example, where identifiers (`NAME`) are typically coloured in black, but when used within a function/class definition are coloured in red (see https://github.com/softdevteam/eco/blob/master/lib/eco/syntaxhighlighter.py#L86).

> You can do automate pretty printing, by pretty printing I means like in Lamdu or Hazel, the line breaking is entirely controlled by the editor (this have good and bad consequences, but we can image ways to remedy the bad ones)

We could do something similar in Eco. Since we have the whole parse tree (and even an AST) we could choose to ignore all whitespace and pretty print it however we like. The reason why Eco doesn't do this is a conscious choice as our goal was to create an editor with features borrowed from structured editors while still being as close to a traditional editor as possible.

**Comment by molikto** [comment]
Thanks for the reply! I guess it is a different idea, but sharing a lot of similarities.
