### ISSUE TITLE
Make current language box more obvious

### ISSUE THREAD

**Issue by vext01** [softdevteam/eco#6]
In the presence of many language boxes it can be really hard to know which box you are in. Although the boxes are different colours:
- The colours can be very similar, making telling them apart hard.
- The colours of the boxes change depending where the cursor is. I find it hard to build a mental map of the program I am editing when it keeps changing appearance.

We discussed putting a dashed border around the current box, whilst also colouring other boxes, but there may be issues with this.

Situation where colours are too subtle:
https://farm1.staticflickr.com/378/19751307154_2387137aa5_o.png

Example of dashed box idea:
https://farm4.staticflickr.com/3720/19753494503_2a8db22524_o.png

Hope this helps, Thanks

**Comment by snim2** [comment]
What was the issue with putting a border around the language boxes? It sounds like a good idea to me.

**Comment by ltratt** [comment]
If you have boxes in boxes in boxes, you'd end up with lots of borders.

That said, some users may like this (even though I'd probably find it too cluttered).

**Comment by ptersilie** [comment]
The dashed line is currently hard to do code-wise, as it is not clear when drawing the source code where it starts and ends. I can have a look at it but I already know that the solution would be quite complex and not worth the trouble, given that we are gonna move onto Eco 2 in the future.
Since dashes are hard I colored the active language box differently instead, which I agree can be a bit confusing.

I agree, that we have to think carefully about fixed colors and how we can improve on the visuals for language boxes.

**Comment by vext01** [comment]
Many thanks!
